
  ******  DRILL DATA LIST  ******

                        Date/Time : Mon Jul 15 08:08:15 2024
                        Host Name : "DESKTOP-7E5HBUS"
                        Directory : "E:\tool\Cadence\SPB_Data"
                        User Name : ³ÂÅåË¹

                       <DRP> File : "C:\Users\³ÂÅåË¹\AppData\Local\Temp\param2.drp"
                         Comments : ""

                   <PNL/PCB> File : "E:\XSL\project\solo\LV07\num2\pcb\XSL24002SCV14.pcb"
                  <MRL/MRDB> File : "D:\Home\cdb\mrdb\pro.mrdb"
                    Drill Machine : "Excellon"

                  Extended Format : Excellon
                   Character Code : ASCII
                    Record Format : Non-Full Storage
                    Record Length : 512
                     NC Data Unit : Millimeters
                Coordinate Format : 000V000
                       Round Unit : 0.00100
        Coordinate Representation : Absolute
                 Omit Coordinates : On
                    Zero Suppress : Leading Zero Suppress
 Coordinates during Tool Exchange : Clear
                         EOB Code : LF
                         EOR Code : SPACE
                         ETB Code : SPACE
                         PAD Code : SPACE

                       <DRD> File : "E:\XSL\project\solo\LV07\num2\Gerber\Gerber-XSL24002SCV14\Hole_TH.drd"
                       <DRL> File : "E:\XSL\project\solo\LV07\num2\Gerber\Gerber-XSL24002SCV14\Hole_TH.drl"

                        List Unit : Millimeters

                            Layer : Only through holes
                Plating attribute : On
                           Figure : Round/Slot/Square
             Way to output oblong : Sequential (Movement rate:0.25000)
             Way to output square : Sequential (Movement rate:0.25000)

                           Origin : (   0.00000,   0.00000)
                           Mirror : OFF
                         Rotation : (   0)
                            Scale : (   1.00000)
                           Offset : (   0.00000,   0.00000)

                       Drill Data : 
 +-----+---------+-------+-------+-----------+-----+-------+---------+-------------+-------------+
 | No. | T_code  | Kind  | Shape |    Size   | Type|Plating|   Hits  |     Move    |   MAX(X,Y)  |
 +-----+---------+-------+-------+-----------+-----+-------+---------+-------------+-------------+
 |   1 |T01      |Normal |Circle |   0.30000 |   1 |    On |     233 |  1925.49233 |  1801.20000 |
 +-----+---------+-------+-------+-----------+-----+-------+---------+-------------+-------------+
 |   2 |T02      |Normal |Circle |   0.40000 |   1 |    On |      32 |-------------|-------------|
 |   2 |T02      |Normal |Circle |   0.40000 |   2 |    On |     966 |-------------|-------------|
 +-----+---------+-------+-------+-----------+-----+-------+---------+-------------+-------------+
 |      T02 Summary                                        |     998 |  4841.31110 |  4542.10000 |
 +-----+---------+-------+-------+-----------+-----+-------+---------+-------------+-------------+
 |   3 |T03      |Normal |Circle |   1.05000 |   1 |    On |      10 |   210.28533 |   206.68000 |
 +-----+---------+-------+-------+-----------+-----+-------+---------+-------------+-------------+
 |   4 |T04      |Normal |Circle |   1.10000 |   1 |    On |       4 |    30.83327 |    24.81000 |
 +-----+---------+-------+-------+-----------+-----+-------+---------+-------------+-------------+
 |      Total                                              |    1245 |  7007.92203 |  6574.79000 |
 +---------------------------------------------------------+---------+-------------+-------------+

                        Data Area : (   0.80000,   5.00000)-(  85.00000,  98.80000)
